name: wawa_kalu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.3.2
  audioplayers: ^6.6.0
  google_fonts: ^8.1.0
  vibration: ^3.1.8
  shared_preferences: ^2.5.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sonidos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/WawaKalu_icono.png"

  adaptive_icon_foreground: "assets/images/WawaKalu_icono.png"
  adaptive_icon_background: "#00000000"

  web:
    generate: true
    image_path: "assets/images/WawaKalu_icono.png"
    background_color: "#FAF7F2"
    theme_color: "#7B2CBF"